AllCops:
  TargetRubyVersion: 3.3.0
  NewCops: enable
Layout/EndOfLine:
  Enabled: true
  EnforcedStyle: lf

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/ClassVars:
  Enabled: false
Style/Documentation:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Style/GlobalVars:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/BlockLength:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
